src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    const STATUS_INACTIVE = 0;
    const STATUS_ACTIVE = 1;
    const STATUS_ARCHIVE = 2;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string', nullable: true)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 8, max: 200, minMessage: "Votre mot de passe doit contenir au moins {{ limit }} caratères")]
    #[Assert\NotCompromisedPassword(message: "Ce mot de passe est compromis, veuillez en choisir un autre.")]
    #[Assert\NotEqualTo(propertyPath: 'email',message: "Votre mot de passe ne doit pas contenir votre email.")]
    #[Assert\NotEqualTo(propertyPath: 'histologe',message: "Votre mot de passe ne doit pas contenir 'histologe'")]
    private $password;

    #[ORM\OneToMany(mappedBy: 'modifiedBy', targetEntity: Signalement::class)]
    private $signalementsModified;


    #[ORM\OneToMany(mappedBy: 'createdBy', targetEntity: Suivi::class, orphanRemoval: true)]
    private $suivis;

    #[ORM\ManyToOne(targetEntity: Partenaire::class, inversedBy: 'users')]
    private $partenaire;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $prenom;


    #[ORM\Column(type: 'integer')]
    private $statut;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private $lastLoginAt;

    private $newsActivitiesSinceLastLogin;

    #[ORM\Column(type: 'boolean')]
    private $isGenerique;

    #[ORM\Column(type: 'boolean')]
    private $isMailingActive;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Job::class, orphanRemoval: true)]
    private $jobs;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Notification::class)]
    private $notifications;

    public function __construct()
    {
        $this->suivis = new ArrayCollection();
        $this->statut = self::STATUS_INACTIVE;
        $this->jobs = new ArrayCollection();
        $this->notifications = new ArrayCollection();
    }

    /*public function setId($id): ?self
    {
        $this->id = $id;
        return $this;
    }*/

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string|null
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Signalement[]
     */
    public function getSignalementsModified(): Collection
    {
        return $this->signalementsModified;
    }

    public function addSignalementModified(Signalement $signalement): self
    {
        if (!$this->signalementsModified->contains($signalement)) {
            $this->signalementsModified[] = $signalement;
            $signalement->setModifiedBy($this);
        }

        return $this;
    }

    public function removeSignalementModified(Signalement $signalement): self
    {
        if ($this->signalementsModified->removeElement($signalement)) {
            // set the owning side to null (unless already changed)
            if ($signalement->getModifiedBy() === $this) {
                $signalement->setModifiedBy(null);
            }
        }

        return $this;
    }


    /**
     * @return Collection|Suivi[]
     */
    public function getSuivis(): Collection
    {
        return $this->suivis;
    }

    public function addSuivi(Suivi $suivi): self
    {
        if (!$this->suivis->contains($suivi)) {
            $this->suivis[] = $suivi;
            $suivi->setCreatedBy($this);
        }

        return $this;
    }

    public function removeSuivi(Suivi $suivi): self
    {
        if ($this->suivis->removeElement($suivi)) {
            // set the owning side to null (unless already changed)
            if ($suivi->getCreatedBy() === $this) {
                $suivi->setCreatedBy(null);
            }
        }

        return $this;
    }

    public function getPartenaire(): ?Partenaire
    {
        return $this->partenaire;
    }

    public function setPartenaire(?Partenaire $partenaire): self
    {
        $this->partenaire = $partenaire;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNomComplet()
    {
        return mb_strtoupper($this->nom) . ' ' . ucfirst($this->prenom);
    }

    public function getStatut(): ?int
    {
        return $this->statut;
    }

    public function setStatut(int $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getLastLoginAt(): ?\DateTimeImmutable
    {
        return $this->lastLoginAt;
    }

    public function setLastLoginAt(?\DateTimeImmutable $lastLoginAt): self
    {
        $this->lastLoginAt = $lastLoginAt;

        return $this;
    }

    public function getIsGenerique(): ?bool
    {
        return $this->isGenerique;
    }

    public function setIsGenerique(bool $isGenerique): self
    {
        $this->isGenerique = $isGenerique;

        return $this;
    }


    public function getIsMailingActive(): ?bool
    {
        return $this->isMailingActive;
    }

    public function setIsMailingActive(bool $isMailingActive): self
    {
        $this->isMailingActive = $isMailingActive;

        return $this;
    }

    /**
     * @return Collection|Job[]
     */
    public function getJobs(): Collection
    {
        return $this->jobs;
    }

    public function addJob(Job $job): self
    {
        if (!$this->jobs->contains($job)) {
            $this->jobs[] = $job;
            $job->setUser($this);
        }

        return $this;
    }

    public function removeJob(Job $job): self
    {
        if ($this->jobs->removeElement($job)) {
            // set the owning side to null (unless already changed)
            if ($job->getUser() === $this) {
                $job->setUser(null);
            }
        }

        return $this;
    }

    public function setId(mixed $id_userbo)
    {
        $this->id = $id_userbo;
    }

    /**
     * @return Collection|Notification[]
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): self
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications[] = $notification;
            $notification->setUser($this);
        }

        return $this;
    }

    public function removeNotification(Notification $notification): self
    {
        if ($this->notifications->removeElement($notification)) {
            // set the owning side to null (unless already changed)
            if ($notification->getUser() === $this) {
                $notification->setUser(null);
            }
        }

        return $this;
    }


    public function isAdmin(): bool
    {
        return count(array_intersect(['ROLE_ADMIN','ROLE_ADMIN_TERRITOIRE'], $this->roles)) > 0;
    }
}

templates/back/bug_report/_delete_form.html.twig
<form method="post" action="{{ path('back_user_report_delete', {'id': report.id}) }}" onsubmit="return confirm('Êtes-vous sûre de vouloir taguer ce bug comme résolu ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('user_report_delete_' ~ report.id) }}">
    <button class="fr-btn fr-btn--success fr-fi-check-line fr-btn--sm" title="Taguer comme résolu"></button>
</form>

templates/back/bug_report/index.html.twig
{% extends 'back/base_bo.html.twig' %}

{% block title %}Retours utilisateur{% endblock %}

{% block content %}
    <section class="fr-grid-row fr-grid-row--middle fr-p-5v ">
        <div class="fr-col-6">
            <h1 class="fr-h2 fr-mb-0">Retours utilisateur</h1>
        </div>
        {# <div class="fr-col-6 fr-text--right">
            <a class="fr-btn fr-btn--icon-left fr-fi-add-circle-line" href="{{ path('back_partenaire_new') }}">Ajouter un partenaire</a>
        </div> #}
    </section>
    <section class="fr-col-12 fr-table fr-table--bordered fr-pt-0">
        <table class="fr-display-inline-table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Par</th>
                <th>Contenu</th>
                <th>Capture</th>
                <th>Url</th>
                <th>Route</th>
                <th class="fr-text--right">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for report in reports %}
                <tr class="{% if report.isArchive %}fr-background-alt--green-bourgeon{% else %}fr-background-alt--red-marianne{% endif %}">
                    <td>{{ report.id }}</td>
                    <td>{{ report.createdAt|date('d/m/Y') }}</td>
                    <td>{{ report.createdBy.nomComplet }}</td>
                    <td>{{ report.content }}</td>
                    <td>
                        <button class="fr-btn fr-fi-eye-fill"
                                onclick="img_box('{{ asset('_capture/'~report.capture) }}')"></button>
                    </td>
                    <td><a class="fr-link" href="{{ report.url }}">{{ report.url }}</a></td>
                    <td>{{ report.route }}</td>
                    <td class="fr-text--right">
                        {% if not report.isArchive %}
                            {{ include('back/bug_report/_delete_form.html.twig') }}
                        {% else %}
                            <span class="fr-fi-check-line fr-tag--icon-left"> Résolu</span>
                            <span class="fr-hint-text"><small>{{ report.archivedAt|date('d/m/Y') }}</small></span>
                        {% endif %}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8">Aucun report</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </section>


{% endblock %}

templates/back/bug_report/modal_bug.html.twig
<dialog aria-labelledby="fr-bug-report-modal-title" id="fr-bug-report-modal" class="fr-modal" role="dialog" >
    <div class="fr-container fr-container--fluid fr-container-md">
        <div class="fr-grid-row fr-grid-row--center">
            <div class="fr-col-12 fr-col-md-8 fr-col-lg-8">
                <div class="fr-modal__body">
                    <div class="fr-modal__header">
                        <button class="fr-link--close fr-link" aria-controls="fr-bug-report-modal">Fermer</button>
                    </div>
                    <div class="fr-modal__content">
                        <h1 id="fr-bug-report-modal-title" class="fr-modal__title fr-mb-0">
                            <span class="fr-fi-alert-line fr-fi--lg"></span>
                            Votre message au support
                        </h1>
                        <span class="fr-hint-text">Dans le cadre de l'amélioration constante du service Histologe, nous vous invitions à nous contacter si vous rencontrez un problème, avez une suggestion d'amélioration ou une remarque.</span>
                        <div class="fr-grid-row fr-grid-row--middle fr-grid-row--center fr-mt-5w fr-hidden" id="bug-report-success">
                            <div class="fr-col fr-text--center">
                                <h3 class="fr-text-label--green-emeraude"><span class="fr-fi-checkbox-circle-line"></span> Votre message à bien été transmis.</h3>
                            </div>
                        </div>
                        <form action="{{ path('back_bug_report') }}" class="needs-validation fr-hidden" name="bug-report" id="bug-report-form">
                            <div class="fr-input-group">
                                <label class="fr-label" for="bug-report-content">
                                    <strong>Décrivez le ou les problème(s) rencontré(s)</strong><sup class="fr-text-default--error">*</sup>
                                    <span class="fr-hint-text"><strong>Une capture d'écran sera jointe</strong> à votre message.</span>
                                </label>
                                <textarea class="fr-input fr-input--no-resize" id="bug-report-content"
                                          name="bug-report[content]" required minlength="10" rows="10"></textarea>
                                <p class="fr-error-text fr-hidden">
                                    Merci de proposer une rapide description (minimum 10 caractères).
                                </p>
                            </div>
                            <input type="hidden" id="bug-report-route" name="bug-report[route]" value="{{ app.request.get('_route') }}">
                            <input type="hidden" id="bug-report-url"  name="bug-report[url]" value="{{ app.request.uri }}">
                            <input type="hidden" id="bug-report-token"   name="_token" value="{{ csrf_token('user_bug_report') }}">
                        </form>
                    </div>
                    <div class="fr-modal__footer">
                        <ul class="fr-btns-group fr-btns-group--right fr-btns-group--inline-reverse fr-btns-group--inline-lg fr-btns-group--icon-left">
                            <li>
                                <button type="submit" form="bug-report-form" class="fr-btn fr-fi-check-line" id="bug-report-submit" disabled>
                                    Soumettre
                                </button>
                            </li>
                            <li>
                                <button class="fr-btn fr-btn--secondary fr-fi-close-line" aria-controls="fr-bug-report-modal">
                                    Fermer
                                </button>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</dialog>